// apps/mcp/src/tools/init-project.ts
import { z } from 'zod';
import { join } from 'node:path';
import { mkdir, writeFile, readFile } from 'node:fs/promises';
import type { Context } from '../context.js';
import { textResult, errorResult } from '../lib/error.js';
import { projectPaths, isoToday, slugify } from '@mindbase/core';

export const inputSchema = z.object({
  name: z.string().min(1),
  template: z.enum(['empty', 'investigation', 'literature-review', 'market-research', 'reading-companion', 'topic-tracker']).optional().default('empty'),
  mission: z.string().optional().default(''),
});

export const definition = {
  name: 'mindbase_init_project',
  description: 'Scaffold a new Lokyy Brain project with the v2 layout: README.md, context.md, index.yaml, sources/contributors/, sources/research/, sources/raw/, state/, logs/, artifacts/. Idempotent — refuses to overwrite existing project.',
  inputSchema: {
    type: 'object',
    properties: {
      name: { type: 'string', description: 'Project name (will be slugified to project id)' },
      template: { type: 'string', description: 'Template: empty | investigation | literature-review | market-research | reading-companion | topic-tracker' },
      mission: { type: 'string', description: 'Optional one-line project mission' },
    },
    required: ['name'],
  },
};

export async function handle(ctx: Context, rawInput: unknown) {
  const parsed = inputSchema.safeParse(rawInput);
  if (!parsed.success) {
    return errorResult(`Invalid input: ${parsed.error.issues[0]?.message ?? 'parse error'}`);
  }
  const { name, mission } = parsed.data;
  const projectId = slugify(name);
  const projectRoot = join(ctx.dataDir, 'projects', projectId);
  const paths = projectPaths();
  const today = isoToday();

  // Refuse if project already exists.
  try {
    await readFile(join(projectRoot, paths.readme), 'utf-8');
    return errorResult(`Project '${projectId}' already exists. Use a different name or remove it first.`);
  } catch { /* good — does not exist */ }

  // Create directory structure.
  const dirs = [
    projectRoot,
    join(projectRoot, paths.contributorsRoot),
    join(projectRoot, paths.researchDir),
    join(projectRoot, paths.rawDir),
    join(projectRoot, paths.stateRoot),
    join(projectRoot, paths.logsRoot),
    join(projectRoot, paths.artifactsRoot),
  ];
  for (const d of dirs) await mkdir(d, { recursive: true });

  // Render README.md from template.
  const readmeTpl = await readFile(join(ctx.dataDir, '..', 'apps', 'plugin', 'templates', 'README.md.template'), 'utf-8').catch(async () => {
    // Fallback inline template if plugin not installed.
    return `# ${name} — Operations Manual\n\n## Mission\n\n${mission || 'TBD'}\n\n## Contribution Rules\n\n\`\`\`yaml\nstatus_vocab: [wip, blocked, done, superseded]\n\`\`\`\n`;
  });
  const readme = readmeTpl
    .replace(/\{\{project_name\}\}/g, name)
    .replace(/\{\{project_id\}\}/g, projectId)
    .replace(/\{\{mission\}\}/g, mission || 'TBD');
  await writeFile(join(projectRoot, paths.readme), readme, 'utf-8');

  // Render context.md.
  const contextTpl = `# ${name} — Context\n*Last built: ${today}*\n\n## Current Focus\n*Empty — run \`/mb:contribute\` to add entries.*\n\n## Active Topics\n\n## Key Decisions\n\n## Learnings\n\n## Open Questions\n\n## Blockers\n`;
  await writeFile(join(projectRoot, paths.context), contextTpl, 'utf-8');

  // Empty index.yaml seed.
  const indexYaml = `# Auto-generated by /mb:build — do not edit manually.\nproject:\n  id: ${projectId}\n  name: ${name}\n  created: ${today}\nfiles: []\ncontributors: []\n`;
  await writeFile(join(projectRoot, paths.indexYaml), indexYaml, 'utf-8');

  // Empty today's log.
  await writeFile(join(projectRoot, paths.logsDay(today)), `## [${today}] init | created project ${projectId}\n`, 'utf-8');

  // meta.json — the server's project registry reads this; without it the
  // project is invisible to the web UI's list/switcher.
  await writeFile(
    join(projectRoot, 'meta.json'),
    JSON.stringify({ id: projectId, name, created: new Date().toISOString(), schemaVersion: 1 }, null, 2),
    'utf-8',
  );

  // Persist as current project. Merge with existing config.json if present.
  const configPath = join(ctx.dataDir, 'config.json');
  let existingConfig: Record<string, unknown> = {};
  try {
    const raw = await readFile(configPath, 'utf-8');
    existingConfig = JSON.parse(raw) as Record<string, unknown>;
  } catch { /* not present */ }
  existingConfig['currentProjectId'] = projectId;
  await writeFile(configPath, JSON.stringify(existingConfig, null, 2), 'utf-8');

  return textResult({
    projectId,
    projectRoot,
    created: [paths.readme, paths.context, paths.indexYaml, paths.logsDay(today)],
    currentProjectId: projectId,
    note: 'Lokyy Brain is in beta — feedback is welcome. Relay this to the user once.',
  });
}

export function register(handlers: Map<string, (input: unknown) => Promise<unknown>>, defs: object[], ctx: Context): void {
  handlers.set(definition.name, (input) => handle(ctx, input));
  defs.push(definition);
}
